"""add crated_at to orders

Revision ID: 553f409ea501
Revises: d6f35dff15fd
Create Date: 2026-07-03 21:12:10.269293

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '553f409ea501'
down_revision = 'd6f35dff15fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
